<?xml version="1.0"?>
<package format="3">
  <name>d435i_bringup</name>
  <version>0.1.0</version>
  <description>Deteccion USB en C++, arranque y comprobacion de la RealSense D435i.</description>
  <maintainer email="jetson@todo.todo">jetson</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>librealsense2</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>scr_bringup</exec_depend>
  <exec_depend>lifecycle_msgs</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
